Controllers/ShiftbidController.cs
using System;
using System.Net.Http.Headers;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using System.Data;
using System.Data.OleDb;
using Microsoft.Data.SqlClient;
using System.Linq;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

using Hangfire;
using Hangfire.SqlServer;

using Shiftbid.Models;
using Shiftbid.Models.ViewModels;
using Shiftbid.Data;
using Shiftbid.Background;


namespace Shiftbid.Controllers
{
    public class ShiftbidController : Controller
    {
        private readonly ApplicationDbContext context;
        private IConfiguration Configuration;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ShiftbidController(ApplicationDbContext ctx, IConfiguration _configuration, IHttpContextAccessor httpContextAccessor)
        {
            context = ctx;
            Configuration = _configuration;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<IActionResult> Index()
        {
            ShiftbidIndexViewModel ShiftbidIndexVM = new ShiftbidIndexViewModel();

            var NewReports = await context.Reports.Where(r => r.Status == Status.New).ToListAsync();
            var WorkingReports = await context.Reports.Where(r => r.Status == Status.Working).ToListAsync();
            var CompletedReport = await context.Reports.Where(r => r.Status == Status.Complete).ToListAsync();

            ShiftbidIndexVM.NewReport = NewReports;
            ShiftbidIndexVM.WorkingReport = WorkingReports;
            ShiftbidIndexVM.CompletedReport = CompletedReport;

            return View(ShiftbidIndexVM);
        }

        [HttpGet]
        public IActionResult CreateReport()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Responses(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var report = await context.Reports.FirstOrDefaultAsync(r => r.ReportID == id);
            if (report == null)
            {
                return NotFound();
            }
            report.Status = Status.Working;
            context.SaveChanges();

            var shift = context.Shifts.Where(s => s.Report == report && s.Email == null).Select(s => new SelectListItem()
            {
                Value = s.ShiftID.ToString(),
                Text = s.ShiftName
            }).ToList();

            if (shift == null)
            {
                return NotFound();
            }
            ResponsesViewModel responsesViewModel = new ResponsesViewModel();
            responsesViewModel.Shifts = shift;

            BackgroundJob.Enqueue<Background.Background>((bg) => bg.ProcessBGJob(report.ReportID));

            return View(responsesViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Responses(ResponsesViewModel vm)
        {

            if (vm.EmailAddress != null && vm.Shifts != null)
            {
                var selected = Int64.Parse(Request.Form["Shifts"]);
                Shift selectedShift = context.Shifts.FirstOrDefault(s => s.ShiftID == selected);

                selectedShift.Email = vm.EmailAddress;
                Seniority currentSeniority = context.Seniorities.FirstOrDefault(s => s.AgentEmail == vm.EmailAddress);
                currentSeniority.SeniorityState = SeniorityState.Received;
                context.SaveChanges();

                return Content("Success");
            }
            return Content("Fail");
        }

        [HttpPost]
        public async Task<IActionResult> CreateReport(ReportViewModel vm)
        {
            //Create Seniority object with report object added
            if (vm.SeniorityFile != null && vm.ShiftFile != null)
            {
                // Create and add report object to DB
                var datetime = DateTime.Now;
                var report = new Report { ReportName = vm.ReportName, DateTimeCreated = datetime, Status = Status.New };
                var dbReport = context.Reports.Add(report);
                context.SaveChanges();
                // Get Report Object from Context
                report = context.Reports.Where(r => r.ReportName == vm.ReportName).Single();

                //get path
                var MainPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads", report.ReportName);

                //create directory "Uploads" if it doesn't exists
                if (!Directory.Exists(MainPath))
                {
                    Directory.CreateDirectory(MainPath);
                }

                DataTable SeniorityDt = DtCreator(MainPath, vm, "Seniority");
                DataTable ShiftDt = DtCreator(MainPath, vm, "Shift");
                Directory.Delete(MainPath, true);
                foreach (DataRow row in SeniorityDt.Rows.Cast<DataRow>().Skip(1))
                {
                    Seniority sn = new Seniority();
                    for (int i = 0; i < row.ItemArray.Length; i++)
                    {
                        if (i < 1)
                        {
                            sn.SeniorityNumber = Convert.ToInt32(row.ItemArray[i]);
                        }
                        else if (i == 1)
                        {
                            sn.AgentName = (string)row.ItemArray[i];
                        }
                        else
                        {
                            sn.AgentEmail = (string)row.ItemArray[i];
                        }
                    }
                    sn.Report = report;
                    sn.ReportID = report.ReportID;
                    sn.SeniorityState = SeniorityState.New;
                    context.Seniorities.Add(sn);
                }
                await context.SaveChangesAsync();

                foreach (DataRow row in ShiftDt.Rows.Cast<DataRow>().Skip(1))
                {
                    Shift sh = new Shift();
                    for (int i = 0; i < row.ItemArray.Length; i++)
                    {
                        if (i < 1)
                        {
                            sh.ShiftName = (string)row.ItemArray[i];
                        }
                    }
                    sh.Report = report;
                    sh.ReportID = report.ReportID;
                    context.Shifts.Add(sh);
                }
                await context.SaveChangesAsync();

                return RedirectPermanent("~/Shiftbid/Index");
            }
            else
            {
                return View();
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var report = await context.Reports.FirstOrDefaultAsync(r => r.ReportID == id);
            if (report == null)
            {
                return NotFound();
            }
            return View(report);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var report = await context.Reports.FindAsync(id);
            context.Reports.Remove(report);
            await context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public DataTable DtCreator(string MainPath, ReportViewModel vm, string Model)
        {
            if (Model.Equals("Seniority"))
            {
                var filePath = Path.Combine(MainPath, vm.SeniorityFile.FileName);
                //var filePath = vm.SeniorityFile.FileName;
                using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
                {
                    vm.SeniorityFile.CopyTo(stream);
                }

                string conString = this.Configuration.GetConnectionString("ExcelConString");

                DataTable dt = new DataTable();
                conString = string.Format(conString, filePath);

                using (OleDbConnection connExcel = new OleDbConnection(conString))
                {

                    using (OleDbCommand cmdExcel = new OleDbCommand())
                    {
                        using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                        {
                            cmdExcel.Connection = connExcel;

                            //Get the name of First Sheet.
                            connExcel.Open();
                            DataTable dtExcelSchema;
                            dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                            string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                            connExcel.Close();

                            //Read Data from First Sheet.
                            connExcel.Open();
                            cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                            odaExcel.SelectCommand = cmdExcel;
                            odaExcel.Fill(dt);
                            connExcel.Close();
                        }
                    }
                }
                return dt;
            }
            else
            {
                var filePath = Path.Combine(MainPath, vm.ShiftFile.FileName);
                using (System.IO.Stream stream = new FileStream(filePath, FileMode.Create))
                {
                    vm.ShiftFile.CopyTo(stream);
                }

                string conString = this.Configuration.GetConnectionString("ExcelConString");

                DataTable dt = new DataTable();

Views/Shiftbid/CreateReport.cshtml
@model Shiftbid.Models.ViewModels.ReportViewModel

@{
    ViewData["Title"] = "Create Page";
}

<form asp-action="CreateReport" asp-controller="Shiftbid" method="post" enctype="multipart/form-data">
    <input type="hidden" asp-for="ReportID"/>
    <input type="hidden" asp-for="DateTimeCreated"/>
    <div class="mb-3">
        <label class="form-label" asp-for="ReportName"></label>
        <div>
            <input class="form-control" asp-for="ReportName" />
        </div>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="SeniorityFile"></label>
        <input class="form-control" asp-for="SeniorityFile"/>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="ShiftFile"></label>
        <input class="form-control" asp-for="ShiftFile"/>
    </div>
    
    <input class="btn btn-primary" type="submit" />       
</form>

Views/Shiftbid/Delete.cshtml
@model Shiftbid.Models.Report

@{
    ViewData["Title"] = "Delete Page";
}

<h4>Are you sure you want to delete "@Model.ReportName" ?</h4>
<form method="post">
    <input class="btn btn-danger" type="submit" value="Delete">
</form>

Views/Shiftbid/Index.cshtml
@model Shiftbid.Models.ViewModels.ShiftbidIndexViewModel
@{
    ViewData["Title"] = "Shiftbid Index";
}

<h4 class="text-center">Shiftbid Index</h4>
<br>
<a class="btn btn-primary" asp-controller="Shiftbid" asp-action="CreateReport">Create</a>
<hr>
<h4 class="text-center">New Reports</h4>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Report Name</th>
            <th scope="col">Date Time Created</th>
            <th scope="col">Delete</th>
            <th scope="col">Run</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var report in Model.NewReport)
        {
            <tr>
                <td>@report.ReportName</td>
                <td>@report.DateTimeCreated</td>
                <td><a class="btn btn-danger text-white" asp-controller="Shiftbid" asp-action="Delete" asp-route-id=@report.ReportID>Delete</a></td>
                <td><a class="btn btn-success text-white" asp-controller="Shiftbid" asp-action="Responses" asp-route-id=@report.ReportID>Run</a></td>
            </tr>
        }
    </tbody>
</table>
<hr>
<h4 class="text-center">Working Reports</h4>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Report Name</th>
            <th scope="col">Date Time Created</th>
            <th scope="col">Delete</th>
            @* <th scope="col">Run</th> *@
        </tr>
    </thead>
    <tbody>
        @foreach (var report in Model.WorkingReport)
        {
            <tr>
                <td>@report.ReportName</td>
                <td>@report.DateTimeCreated</td>
                <td><a class="btn btn-danger text-white" asp-controller="Shiftbid" asp-action="Delete" asp-route-id=@report.ReportID>Delete</a></td>
                @* <td><a class="btn btn-success text-white" asp-controller="Shiftbid" asp-action="Responses" asp-route-id=@report.ReportID>Run</a></td> *@
            </tr>
        }
    </tbody>
</table>
<hr>
<h4 class="text-center">Completed Reports</h4>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Report Name</th>
            <th scope="col">Date Time Created</th>
            <th scope="col">Download</th>
            @* <th scope="col">Run</th> *@
        </tr>
    </thead>
    <tbody>
        @foreach (var report in Model.CompletedReport)
        {
            <tr>
                <td>@report.ReportName</td>
                <td>@report.DateTimeCreated</td>
                <td><a class="btn btn-danger text-white" asp-controller="Shiftbid" asp-action="Download" asp-route-id=@report.ReportID>Download</a></td>
                @* <td><a class="btn btn-success text-white" asp-controller="Shiftbid" asp-action="Responses" asp-route-id=@report.ReportID>Run</a></td> *@
            </tr>
        }
    </tbody>
</table>

Views/Shiftbid/ReportRun.cshtml
@{
    ViewData["Title"] = "Run Confirmation";
}

<h4 class="text-center">This Report Status Is Moved To "Working"</h4>
<h3 class="text-center">Please use the link below to return to "Shiftbid" page</h3>
<a class="btn btn-primary" asp-controller="Shiftbid" asp-action="Index">Shiftbid</a>

Views/Shiftbid/Responses.cshtml
@model Shiftbid.Models.ViewModels.ResponsesViewModel

@{
    ViewData["Title"] = "Responses";
}

<div class="alert alert-danger text-center" role="alert">
  If you are Admin, please return to Shiftbid Homepage.
</div>
<form action="" method="post">
    <div class="form-group">
        <label asp-for="EmailAddress"></label>
        <input required type="email" class="form-control" placeholder="Enter email" asp-for="EmailAddress">
    </div>
    <div class="form-group">
        <label asp-for="Shifts"></label>
        <select class="form-control" asp-for="Shifts" asp-items="@Model.Shifts"></select>
    </div>
    
    <input class="btn btn-primary" type="submit" value="Submit">
    

    
</form>